/lidar_odometry_mapping:
  ros__parameters:
    base_frame: tip
    child_frame: tip
    debug: true
    imu_integration_enabled: false
    lidar_frame: PandarXT-32
    max_distance: 20.0
    map_frame: lid_odom
    max_points_per_voxel: 13
    odom_downsample: true
    odom_frame: lid_odom
    orientation_covariance: 0.1
    position_covariance: 0.1
    publish_transform: true
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    start_type_description_service: true
    use_sim_time: false
    voxel_factor: 50.0
    voxel_resolution_alpha: 1.5
    voxel_resolution_beta: 0.5

